package com.foodcheats.app.database

import com.foodcheats.app.models.FoodItem

object FoodDatabase {

    private val allFoodsList: List<FoodItem> by lazy { buildDatabase() }

    fun getAllFoods(): List<FoodItem> = allFoodsList

    fun getEatFoods(): List<FoodItem> = allFoodsList.filter { it.type == "eat" }

    fun getCheatFoods(): List<FoodItem> = allFoodsList.filter { it.type == "cheat" }

    fun getFoodById(id: Int): FoodItem? = allFoodsList.find { it.id == id }

    fun getFoodsByMood(mood: String, type: String): List<FoodItem> {
        val filtered = allFoodsList.filter { it.type == type && (it.moodTag.contains(mood) || mood == "any") }
        return filtered.ifEmpty { if (type == "eat") getEatFoods() else getCheatFoods() }
    }

    private fun buildDatabase(): List<FoodItem> = listOf(
        // ========== EAT FOODS ==========
        FoodItem(1, "Quinoa Buddha Bowl", "Grains & Bowls", "eat", "🥗",
            "A nourishing bowl loaded with quinoa, roasted veggies, chickpeas, and tahini dressing.",
            420, 18.0, 52.0, 14.0, 9.0, 9, 8, "25 min", "Global",
            "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800",
            "happy,focused,tired",
            listOf("1 cup quinoa", "1 can chickpeas", "1 cup spinach", "1 avocado", "Cherry tomatoes", "2 tbsp tahini", "1 lemon", "Olive oil", "Salt & pepper"),
            listOf("Cook quinoa in 2 cups water for 15 minutes.", "Roast chickpeas with olive oil and cumin at 200°C for 20 min.", "Assemble bowl: quinoa base, chickpeas, spinach, sliced avocado, tomatoes.", "Mix tahini with lemon juice and water for dressing.", "Drizzle dressing and serve warm."),
            listOf("vegan", "gluten-free", "high-protein"), "None"),

        FoodItem(2, "Grilled Salmon", "Seafood", "eat", "🐟",
            "Omega-3 rich grilled salmon with herbs, served with steamed greens.",
            380, 42.0, 5.0, 18.0, 2.0, 9, 9, "20 min", "Mediterranean",
            "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800",
            "focused,tired,stressed",
            listOf("200g salmon fillet", "2 cloves garlic", "1 lemon", "Fresh dill", "Olive oil", "Salt", "Black pepper", "1 cup broccoli"),
            listOf("Marinate salmon with garlic, lemon juice, dill, and olive oil for 15 min.", "Heat grill pan on high heat.", "Grill salmon 4-5 minutes per side.", "Steam broccoli until tender-crisp.", "Serve salmon over greens with lemon wedge."),
            listOf("high-protein", "omega-3", "gluten-free"), "Fish"),

        FoodItem(3, "Avocado Toast", "Breakfast", "eat", "🥑",
            "Whole grain toast topped with smashed avocado, cherry tomatoes and a poached egg.",
            310, 14.0, 28.0, 16.0, 7.0, 8, 9, "10 min", "Modern",
            "https://www.rootsandradishes.com/wp-content/uploads/2017/08/avocado-toast-with-everything-bagel-seasoning-feat.jpg",
            "happy,focused,energetic",
            listOf("2 slices whole grain bread", "1 ripe avocado", "2 eggs", "Cherry tomatoes", "Red chilli flakes", "Salt", "Lemon juice"),
            listOf("Toast the bread until golden.", "Mash avocado with lemon juice and salt.", "Poach eggs in simmering water for 3 minutes.", "Spread avocado on toast, top with egg and tomatoes.", "Sprinkle chilli flakes."),
            listOf("vegetarian", "high-fiber"), "Eggs, Gluten"),

        FoodItem(4, "Greek Yogurt Parfait", "Breakfast", "eat", "🫙",
            "Creamy Greek yogurt layered with granola, mixed berries, and honey.",
            280, 20.0, 35.0, 6.0, 3.0, 9, 8, "5 min", "Greek",
            "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800",
            "happy,energetic,morning",
            listOf("200g Greek yogurt", "1/2 cup granola", "1 cup mixed berries", "2 tbsp honey", "Chia seeds"),
            listOf("Layer yogurt at the bottom of a glass.", "Add a layer of granola.", "Top with mixed berries.", "Drizzle honey and sprinkle chia seeds."),
            listOf("vegetarian", "high-protein", "probiotic"), "Dairy, Nuts"),

        FoodItem(5, "Chicken Stir Fry", "Main Course", "eat", "🍗",
            "Lean chicken breast with colourful vegetables in a light soy-ginger sauce.",
            350, 38.0, 22.0, 10.0, 4.0, 8, 9, "20 min", "Asian",
            "https://maplejubilee.com/wp-content/uploads/2021/07/Chicken-stir-fry-V1.jpg",
            "tired,hungry,energetic",
            listOf("200g chicken breast", "1 cup broccoli", "1 bell pepper", "1 carrot", "2 tbsp soy sauce", "1 tsp ginger", "3 cloves garlic", "Sesame oil"),
            listOf("Slice chicken into thin strips.", "Heat sesame oil in wok on high heat.", "Stir fry chicken until golden, set aside.", "Fry garlic and ginger, add vegetables.", "Add chicken back, pour soy sauce, toss well."),
            listOf("high-protein", "low-carb", "gluten-free"), "Soy"),

        FoodItem(6, "Lentil Soup", "Soup", "eat", "🍲",
            "Hearty red lentil soup with cumin, turmeric, and a squeeze of lemon.",
            290, 18.0, 42.0, 5.0, 12.0, 9, 7, "30 min", "Middle Eastern",
            "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800",
            "stressed,cold,tired",
            listOf("1 cup red lentils", "1 onion", "3 cloves garlic", "1 tsp cumin", "1 tsp turmeric", "1 tomato", "4 cups vegetable broth", "Lemon", "Olive oil"),
            listOf("Sauté onion and garlic in olive oil.", "Add cumin and turmeric, cook 1 minute.", "Add lentils, tomato and broth.", "Simmer 20 minutes until lentils are soft.", "Blend partially, squeeze lemon and serve."),
            listOf("vegan", "high-protein", "high-fiber"), "None"),

        FoodItem(7, "Oatmeal with Berries", "Breakfast", "eat", "🥣",
            "Steel-cut oats topped with seasonal berries, nuts and a drizzle of maple syrup.",
            320, 10.0, 52.0, 8.0, 6.0, 9, 7, "15 min", "American",
            "https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=800",
            "morning,energetic,focused",
            listOf("1 cup rolled oats", "2 cups milk", "1 cup strawberries", "1/4 cup blueberries", "2 tbsp walnuts", "1 tbsp maple syrup", "Cinnamon"),
            listOf("Bring milk to a boil.", "Add oats, reduce heat and cook 5 minutes.", "Stir occasionally until creamy.", "Top with berries, walnuts and maple syrup.", "Sprinkle cinnamon and serve warm."),
            listOf("vegetarian", "heart-healthy", "high-fiber"), "Gluten, Dairy, Nuts"),

        FoodItem(8, "Egg White Omelette", "Breakfast", "eat", "🍳",
            "Fluffy egg white omelette with spinach, mushrooms and feta cheese.",
            180, 22.0, 6.0, 7.0, 1.0, 9, 8, "10 min", "Continental",
            "https://images.unsplash.com/photo-1510693206972-df098062cb71?w=800",
            "focused,morning,diet",
            listOf("4 egg whites", "1 cup spinach", "1/2 cup mushrooms", "50g feta", "Salt", "Black pepper", "Olive oil spray"),
            listOf("Whisk egg whites until frothy.", "Sauté mushrooms and spinach in pan.", "Pour egg whites over vegetables.", "Cook until set, fold with feta inside."),
            listOf("high-protein", "low-carb", "gluten-free", "vegetarian"), "Eggs, Dairy"),

        FoodItem(9, "Brown Rice Khichdi", "Indian Main", "eat", "🍚",
            "A comforting Indian one-pot dish of brown rice and moong dal with light spices.",
            310, 14.0, 54.0, 6.0, 5.0, 9, 7, "30 min", "Indian",
            "https://img-cdn.publive.online/fit-in/640x430/filters:format(webp)/sanjeev-kapoor/media/media_files/lCEcM1TGTODdp7xsGYu5.JPG",
            "sick,tired,stressed,comfort",
            listOf("1/2 cup brown rice", "1/2 cup moong dal", "1 tsp ghee", "Cumin seeds", "1/4 tsp turmeric", "Salt", "3 cups water", "Ginger"),
            listOf("Wash and soak rice and dal for 30 min.", "Heat ghee, add cumin seeds and ginger.", "Add rice and dal, turmeric and salt.", "Add water, pressure cook for 3 whistles.", "Serve warm with a dollop of ghee."),
            listOf("vegetarian", "easy-to-digest", "gluten-free"), "None"),

        FoodItem(10, "Tuna Salad", "Salad", "eat", "🥗",
            "Protein-packed tuna with cucumber, cherry tomatoes, olives and a lemon vinaigrette.",
            280, 35.0, 12.0, 8.0, 3.0, 9, 8, "10 min", "Mediterranean",
            "https://littlespoonfarm.com/wp-content/uploads/2021/08/tuna-salad-recipe-card.jpg",
            "quick,focused,diet",
            listOf("1 can tuna", "1 cucumber", "Cherry tomatoes", "Black olives", "Red onion", "Lemon", "Olive oil", "Salt", "Parsley"),
            listOf("Drain and flake tuna into a bowl.", "Chop cucumber, tomatoes and red onion.", "Mix all vegetables with tuna.", "Dress with lemon juice and olive oil.", "Season with salt and garnish with parsley."),
            listOf("high-protein", "gluten-free", "low-carb"), "Fish"),

        FoodItem(11, "Chickpea Salad", "Salad", "eat", "🧆",
            "Spiced roasted chickpeas with cucumber, pomegranate and mint yogurt dressing.",
            320, 16.0, 44.0, 9.0, 11.0, 9, 8, "20 min", "Middle Eastern",
            "https://th.bing.com/th/id/R.fb573a92d767894c71d69dcc98b89851?rik=hLXqdTQVevI%2bFQ&riu=http%3a%2f%2fwww.delishhealthlife.com%2fwp-content%2fuploads%2f2024%2f03%2fmediterranean-chickpea-salad-5.jpg&ehk=SMeJVA0k3mt2O%2bAEDg%2b8p2xPg%2f1ytN2W3b4QiQ9E9I0%3d&risl=&pid=ImgRaw&r=0",
            "happy,energetic,summer",
            listOf("2 cans chickpeas", "1 cucumber", "1/2 cup pomegranate seeds", "Fresh mint", "Greek yogurt", "Lemon", "Cumin", "Olive oil"),
            listOf("Roast chickpeas with cumin and olive oil at 200°C for 20 min.", "Dice cucumber finely.", "Mix yogurt with lemon juice and mint.", "Combine chickpeas, cucumber and pomegranate.", "Drizzle with mint yogurt dressing."),
            listOf("vegetarian", "high-fiber", "high-protein"), "Dairy"),

        FoodItem(12, "Palak Paneer", "Indian Main", "eat", "🥬",
            "Velvety spinach curry with soft paneer cubes - a nutritional powerhouse.",
            340, 20.0, 18.0, 18.0, 6.0, 8, 9, "30 min", "Indian",
            "https://cdn.vegkit.com/wp-content/uploads/sites/2/2024/02/18160127/palak_tofu_paneer_1.jpg",
            "happy,comfort,hungry",
            listOf("200g paneer", "400g spinach", "1 onion", "2 tomatoes", "Ginger", "Garlic", "Cumin", "Garam masala", "Cream", "Oil"),
            listOf("Blanch spinach and blend to a smooth puree.", "Fry onion, garlic and ginger until golden.", "Add tomatoes and cook until mushy.", "Add spinach puree and spices, simmer 10 min.", "Add paneer cubes and cream, serve hot."),
            listOf("vegetarian", "high-protein", "calcium-rich"), "Dairy"),

        FoodItem(13, "Banana Smoothie Bowl", "Breakfast", "eat", "🍌",
            "Thick frozen banana smoothie topped with granola, chia seeds and sliced fruit.",
            350, 8.0, 68.0, 6.0, 5.0, 8, 9, "10 min", "Modern",
            "https://www.darngoodveggies.com/wp-content/uploads/2021/08/Banana-Smoothie-Bowl-6-scaled.jpg",
            "happy,morning,energetic",
            listOf("2 frozen bananas", "1/2 cup almond milk", "1/2 cup granola", "1 tbsp chia seeds", "Fresh berries", "Coconut flakes", "Honey"),
            listOf("Blend frozen bananas with almond milk until thick.", "Pour into a bowl.", "Top with granola, chia seeds, berries, coconut.", "Drizzle honey and serve immediately."),
            listOf("vegan", "gluten-free", "potassium-rich"), "Nuts"),

        FoodItem(14, "Sweet Potato Black Bean Bowl", "Bowls", "eat", "🍠",
            "Roasted sweet potato with black beans, corn, salsa and lime crema.",
            410, 15.0, 62.0, 11.0, 13.0, 9, 9, "35 min", "Mexican",
            "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800",
            "happy,hungry,comfort",
            listOf("2 sweet potatoes", "1 can black beans", "1 cup corn", "Salsa", "Greek yogurt", "Lime", "Cumin", "Chilli powder", "Olive oil"),
            listOf("Cube sweet potatoes and roast at 200°C with cumin and olive oil for 25 min.", "Heat black beans with cumin and chilli.", "Mix yogurt with lime juice for crema.", "Assemble bowl with sweet potato, beans, corn.", "Top with salsa and lime crema."),
            listOf("vegan", "high-fiber", "vitamin-A-rich"), "None"),

        FoodItem(15, "Dal Tadka", "Indian Main", "eat", "🍛",
            "Yellow lentils tempered with ghee, mustard seeds and dried red chillies.",
            280, 15.0, 38.0, 8.0, 9.0, 9, 8, "30 min", "Indian",
            "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/04/dal-tadka-recipe-500x500.jpg",
            "comfort,tired,hungry",
            listOf("1 cup toor dal", "1 onion", "2 tomatoes", "Ginger", "Garlic", "Cumin seeds", "Mustard seeds", "Dried red chillies", "Ghee", "Turmeric"),
            listOf("Boil dal with turmeric until soft.", "Heat ghee in small pan, add mustard and cumin.", "Add dried chillies, onion, garlic, ginger.", "Add tomatoes, cook until soft.", "Pour tadka over dal and serve with rice."),
            listOf("vegetarian", "high-protein", "gluten-free"), "None"),

        FoodItem(16, "Fresh Fruit Salad", "Snack", "eat", "🍑",
            "Seasonal fresh fruit tossed with mint, lime and a hint of chaat masala.",
            150, 2.0, 36.0, 1.0, 4.0, 10, 9, "10 min", "Universal",
            "https://www.eatingwell.com/thmb/sIf2Z1oNy9UjunVXOCBG5tHAav4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/4518422-8b9bac307f7a4d7fb4379b8c647b806d.jpg",
            "happy,summer,light,snack",
            listOf("1 cup watermelon", "1 mango", "1 apple", "Grapes", "Orange", "Fresh mint", "Lime juice", "Chaat masala", "Honey"),
            listOf("Cut all fruits into bite-sized pieces.", "Toss in a bowl.", "Add lime juice and honey.", "Sprinkle chaat masala and fresh mint.", "Refrigerate 15 min and serve cold."),
            listOf("vegan", "gluten-free", "vitamin-C-rich"), "None"),

        FoodItem(17, "Paneer Tikka", "Indian Snack", "eat", "🧀",
            "Marinated paneer grilled in the oven with peppers and onions.",
            290, 22.0, 12.0, 17.0, 2.0, 8, 9, "40 min", "Indian",
            "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800",
            "happy,party,hungry",
            listOf("250g paneer", "Greek yogurt", "Tandoori masala", "Bell peppers", "Onion", "Ginger-garlic paste", "Lemon", "Oil"),
            listOf("Cut paneer, peppers and onion into cubes.", "Mix yogurt with tandoori masala and ginger-garlic paste.", "Marinate paneer and veggies for 30 min.", "Skewer and grill/bake at 220°C for 15 min.", "Serve with mint chutney and lemon."),
            listOf("vegetarian", "high-protein"), "Dairy"),

        FoodItem(18, "Moong Dal Chilla", "Breakfast", "eat", "🥞",
            "Protein-rich green moong dal pancakes with ginger, green chilli and coriander.",
            240, 16.0, 30.0, 5.0, 6.0, 9, 8, "20 min", "Indian",
            "https://www.funfoodfrolic.com/wp-content/uploads/2021/08/Dal-Cheela-Thumbnail.jpg",
            "morning,energetic,quick",
            listOf("1 cup moong dal", "1 green chilli", "Ginger", "Coriander", "Salt", "Cumin", "Oil"),
            listOf("Soak moong dal for 4-6 hours.", "Blend with ginger, chilli, cumin and salt.", "Stir in chopped coriander.", "Cook thin pancakes on non-stick pan with oil.", "Serve with green chutney."),
            listOf("vegetarian", "high-protein", "gluten-free"), "None"),

        FoodItem(19, "Vegetable Soup", "Soup", "eat", "🥣",
            "Light and nourishing clear soup packed with seasonal vegetables and herbs.",
            120, 5.0, 20.0, 2.0, 5.0, 10, 7, "25 min", "Universal",
            "https://www.allrecipes.com/thmb/p4F_knUDCrUNusNOTyjY_dCp8d4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/13338-quick-and-easy-vegetable-soup-DDMFS-4x3-402702f59e7a41519515cecccaba1b80.jpg",
            "sick,tired,light,cold",
            listOf("Carrots", "Celery", "Zucchini", "Green beans", "Tomatoes", "Onion", "Garlic", "Vegetable broth", "Herbs", "Pepper"),
            listOf("Dice all vegetables into small pieces.", "Sauté onion and garlic until soft.", "Add remaining vegetables and broth.", "Simmer 15-20 minutes until tender.", "Season with herbs, salt and pepper."),
            listOf("vegan", "gluten-free", "low-calorie"), "None"),

        FoodItem(20, "Sprout Salad", "Salad", "eat", "🌱",
            "Antioxidant-rich mixed sprout salad with lemon, tomatoes and chaat masala.",
            180, 12.0, 26.0, 3.0, 8.0, 10, 7, "10 min", "Indian",
            "https://www.funfoodfrolic.com/wp-content/uploads/2020/09/Sprout-Salad-Thumbnail.jpg",
            "energetic,morning,diet",
            listOf("1 cup mixed sprouts", "Tomatoes", "Cucumber", "Onion", "Green chilli", "Lemon juice", "Chaat masala", "Coriander"),
            listOf("Steam sprouts lightly or use raw.", "Finely chop all vegetables.", "Mix everything together.", "Add lemon juice and chaat masala.", "Garnish with coriander and serve."),
            listOf("vegan", "gluten-free", "high-fiber"), "None"),

        FoodItem(21, "Baked Chicken", "Main Course", "eat", "🍖",
            "Herb-crusted baked chicken breast with roasted garlic and lemon.",
            320, 45.0, 4.0, 13.0, 1.0, 9, 8, "40 min", "Continental",
            "https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=800",
            "focused,muscle,diet",
            listOf("2 chicken breasts", "Garlic powder", "Paprika", "Italian herbs", "Lemon", "Olive oil", "Salt", "Pepper"),
            listOf("Preheat oven to 200°C.", "Rub chicken with olive oil and all spices.", "Bake 25-30 minutes until cooked through.", "Rest 5 minutes before slicing.", "Serve with lemon wedges and veggies."),
            listOf("high-protein", "low-carb", "gluten-free"), "None"),

        FoodItem(22, "Green Detox Smoothie", "Drinks", "eat", "🥤",
            "Energising green smoothie with spinach, cucumber, apple, ginger and lemon.",
            130, 3.0, 28.0, 1.0, 3.0, 10, 7, "5 min", "Modern",
            "https://www.cubesnjuliennes.com/wp-content/uploads/2022/02/Green-Detox-Smoothie-Recipe.jpg",
            "detox,morning,energetic",
            listOf("1 cup spinach", "1/2 cucumber", "1 apple", "1 tsp ginger", "Lemon juice", "1 cup water", "Mint leaves"),
            listOf("Wash all ingredients thoroughly.", "Chop apple and cucumber roughly.", "Blend everything with water until smooth.", "Strain if desired.", "Serve immediately over ice."),
            listOf("vegan", "gluten-free", "low-calorie", "detox"), "None"),

        FoodItem(23, "Curd Rice", "Indian Main", "eat", "🍚",
            "Cooling South Indian yogurt rice tempered with mustard seeds and curry leaves.",
            280, 9.0, 46.0, 7.0, 1.0, 8, 8, "20 min", "South Indian",
            "https://www.cookwithmanali.com/wp-content/uploads/2015/01/Curd-Rice-South-Indian.jpg",
            "sick,comfort,summer,tired",
            listOf("1 cup cooked rice", "1 cup curd", "Mustard seeds", "Curry leaves", "Green chilli", "Ginger", "Coriander", "Pomegranate", "Oil"),
            listOf("Let cooked rice cool slightly.", "Mix with curd, salt and green chilli.", "Heat oil, add mustard seeds and curry leaves.", "Pour tadka over curd rice.", "Garnish with pomegranate and coriander."),
            listOf("vegetarian", "probiotic", "gluten-free"), "Dairy"),

        FoodItem(24, "Roasted Vegetables", "Side Dish", "eat", "🥦",
            "A rainbow of seasonal vegetables roasted with herbs and balsamic glaze.",
            160, 4.0, 28.0, 5.0, 7.0, 10, 8, "30 min", "Mediterranean",
            "https://www.wellplated.com/wp-content/uploads/2021/12/What-to-do-with-roasted-vegetables.jpg",
            "light,diet,vegan",
            listOf("Zucchini", "Bell peppers", "Eggplant", "Cherry tomatoes", "Broccoli", "Olive oil", "Balsamic", "Garlic", "Herbs"),
            listOf("Preheat oven to 200°C.", "Cut all vegetables into similar-sized pieces.", "Toss with olive oil, balsamic, garlic and herbs.", "Roast 25 minutes, tossing once midway.", "Serve warm or at room temperature."),
            listOf("vegan", "gluten-free", "low-calorie"), "None"),

        FoodItem(25, "Masoor Dal Soup", "Soup", "eat", "🍲",
            "Warming red lentil and tomato soup with Indian spices — high in iron and protein.",
            260, 16.0, 36.0, 5.0, 10.0, 9, 8, "25 min", "Indian",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6N_B46PSG6fdyCP9xW9ZhzIi_g2RvrnFvUw&s",
            "cold,tired,comfort",
            listOf("1 cup masoor dal", "2 tomatoes", "1 onion", "Ginger", "Garlic", "Cumin", "Coriander powder", "Turmeric", "Oil", "Coriander leaves"),
            listOf("Pressure cook dal with tomatoes until soft.", "Sauté onion, garlic and ginger until golden.", "Add all spices and cook 1 minute.", "Combine with dal, simmer 10 minutes.", "Garnish with fresh coriander."),
            listOf("vegan", "gluten-free", "iron-rich"), "None"),

        FoodItem(26, "Tofu Scramble", "Breakfast", "eat", "🍳",
            "Savoury tofu scramble with turmeric, spinach and cherry tomatoes.",
            220, 18.0, 12.0, 10.0, 3.0, 9, 7, "15 min", "Vegan",
            "https://plantbasedonabudget.com/wp-content/uploads/2023/01/87-Tofu-Scramble-Plant-Based-on-a-Budget-1-2.jpg",
            "morning,vegan,diet",
            listOf("200g firm tofu", "Spinach", "Cherry tomatoes", "Turmeric", "Nutritional yeast", "Garlic", "Salt", "Oil"),
            listOf("Crumble tofu in pan with oil.", "Add turmeric, garlic, salt.", "Add spinach and tomatoes.", "Cook until everything is combined.", "Serve on toast or bowl."),
            listOf("vegan", "high-protein", "gluten-free"), "Soy"),

        FoodItem(27, "Rajma Chawal", "Indian Main", "eat", "🫘",
            "Hearty kidney bean curry served with steamed basmati rice — a protein-rich classic.",
            480, 20.0, 72.0, 10.0, 14.0, 8, 9, "45 min", "North Indian",
            "https://www.secondrecipe.com/wp-content/uploads/2017/08/rajma-chawal-1-500x500.jpg",
            "comfort,hungry,happy",
            listOf("1 cup rajma", "2 onions", "3 tomatoes", "Ginger-garlic paste", "Rajma masala", "Oil", "Ghee", "Basmati rice"),
            listOf("Soak rajma overnight and pressure cook.", "Sauté onions until golden.", "Add ginger-garlic, tomatoes and masala.", "Add rajma with water, simmer 20 min.", "Serve with steamed rice and ghee."),
            listOf("vegetarian", "high-fiber", "high-protein"), "None"),

        FoodItem(28, "Poha", "Breakfast", "eat", "🍚",
            "Light and flavourful flattened rice with peanuts, mustard seeds and fresh lemon.",
            290, 7.0, 50.0, 6.0, 3.0, 8, 9, "15 min", "Indian",
            "https://vegecravings.com/wp-content/uploads/2016/12/Aloo-Poha-Recipe-Step-By-Step-Instructions-scaled.jpg",
            "morning,quick,light",
            listOf("2 cups thick poha", "Peanuts", "Mustard seeds", "Curry leaves", "Green chilli", "Onion", "Turmeric", "Lemon", "Coriander"),
            listOf("Rinse poha and let drain.", "Fry peanuts until golden, set aside.", "Add mustard seeds, curry leaves to oil.", "Add onion, chilli, turmeric.", "Add poha, lemon and peanuts, toss well."),
            listOf("vegetarian", "gluten-free", "iron-rich"), "Peanuts"),

        FoodItem(29, "Dhokla", "Indian Snack", "eat", "🟡",
            "Steamed fermented chickpea cake — light, spongy and probiotic-rich.",
            160, 7.0, 26.0, 3.0, 2.0, 9, 8, "40 min", "Gujarati",
            "https://shwetainthekitchen.com/wp-content/uploads/2023/04/instant-khaman-dhokla-recipe.jpg",
            "snack,light,happy",
            listOf("1 cup besan", "Curd", "Ginger", "Green chilli", "Eno fruit salt", "Mustard seeds", "Curry leaves", "Sugar", "Lemon"),
            listOf("Mix besan, curd, ginger, chilli and salt.", "Rest batter 30 min.", "Add eno, mix and steam 15 minutes.", "Prepare tempering with mustard and curry leaves.", "Pour over dhokla, serve with chutney."),
            listOf("vegetarian", "probiotic", "gluten-free"), "Dairy"),

        FoodItem(30, "Overnight Oats", "Breakfast", "eat", "🥣",
            "Effortless no-cook oats soaked overnight with chia seeds and fruit.",
            330, 12.0, 54.0, 8.0, 7.0, 9, 8, "5 min", "Modern",
            "https://www.tasteofhome.com/wp-content/uploads/2024/09/Overnight-Maple-Oatmeal_EXPS_TOHD24_160824_ChristineMa_7.jpg",
            "morning,quick,meal-prep",
            listOf("1 cup rolled oats", "1 cup almond milk", "2 tbsp chia seeds", "1 tbsp honey", "Vanilla extract", "Berries"),
            listOf("Mix oats, almond milk, chia seeds, honey and vanilla.", "Pour into jar.", "Refrigerate overnight.", "In the morning, top with fresh berries.", "Enjoy cold or warm."),
            listOf("vegan", "high-fiber", "meal-prep"), "Gluten, Nuts"),

        // ========== CHEAT FOODS ==========
        FoodItem(31, "Margherita Pizza", "Italian", "cheat", "🍕",
            "Classic wood-fired style pizza with San Marzano tomatoes and fresh mozzarella.",
            580, 22.0, 72.0, 22.0, 4.0, 5, 10, "30 min", "Italian",
            "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800",
            "happy,party,weekend",
            listOf("Pizza dough", "San Marzano tomatoes", "Fresh mozzarella", "Fresh basil", "Olive oil", "Sea salt", "Garlic"),
            listOf("Stretch pizza dough on floured surface.", "Spread crushed tomatoes.", "Add torn mozzarella and drizzle oil.", "Bake at 250°C for 12 minutes.", "Add fresh basil after baking."),
            listOf("vegetarian"), "Gluten, Dairy"),

        FoodItem(32, "Baked French Fries", "Snack", "cheat", "🍟",
            "Oven-baked potato wedges seasoned with paprika and herbs — guilt-free fries!",
            280, 5.0, 50.0, 7.0, 5.0, 6, 9, "35 min", "American",
            "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800",
            "craving,snack,weekend",
            listOf("4 potatoes", "Olive oil", "Paprika", "Garlic powder", "Salt", "Mixed herbs"),
            listOf("Cut potatoes into wedges.", "Toss with olive oil and all spices.", "Spread on baking sheet — don't overlap.", "Bake at 220°C for 25-30 min.", "Serve with ketchup or yogurt dip."),
            listOf("vegan", "gluten-free", "baked-not-fried"), "None"),

        FoodItem(33, "Grilled Chicken Burger", "Fast Food", "cheat", "🍔",
            "Grilled (not fried!) chicken burger with lettuce, tomato and light mayo on whole grain bun.",
            520, 38.0, 46.0, 18.0, 4.0, 6, 10, "25 min", "American",
            "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800",
            "hungry,weekend,party",
            listOf("Chicken breast", "Whole grain bun", "Lettuce", "Tomato", "Light mayo", "Mustard", "Red onion", "Pickles"),
            listOf("Season and grill chicken breast.", "Toast the bun lightly.", "Spread mayo and mustard on bun.", "Layer lettuce, tomato, chicken, pickles.", "Serve with baked fries."),
            listOf("high-protein"), "Gluten, Eggs, Dairy"),

        FoodItem(34, "Chocolate Banana Pancakes", "Breakfast", "cheat", "🥞",
            "Fluffy 2-ingredient banana oat pancakes with dark chocolate chips.",
            380, 9.0, 60.0, 12.0, 5.0, 6, 10, "15 min", "Modern",
            "https://avirtualvegan.com/wp-content/uploads/2021/01/Chocolate-Banana-Pancakes-9.jpg",
            "happy,weekend,sweet",
            listOf("2 bananas", "2 eggs", "1/2 cup oats", "Dark chocolate chips", "Vanilla", "Honey", "Butter"),
            listOf("Mash bananas with eggs and vanilla.", "Stir in oats and chocolate chips.", "Cook small pancakes on buttered pan.", "Flip when bubbles form.", "Serve with honey drizzle."),
            listOf("vegetarian", "gluten-free"), "Eggs, Dairy"),

        FoodItem(35, "Masala Dosa", "South Indian", "cheat", "🫔",
            "Crispy fermented rice crepe with spiced potato filling — street food heaven.",
            450, 9.0, 72.0, 14.0, 4.0, 6, 10, "45 min", "South Indian",
            "https://aroundtheyum.com/wp-content/uploads/2025/06/masala-dosa-recipe-.jpg",
            "weekend,happy,hungry",
            listOf("Dosa batter", "Potatoes", "Onion", "Mustard seeds", "Curry leaves", "Turmeric", "Oil", "Coconut chutney", "Sambar"),
            listOf("Boil and mash potatoes.", "Make spiced filling with onion and spices.", "Spread dosa batter thin on hot griddle.", "Fill with potato mixture.", "Roll and serve with chutney and sambar."),
            listOf("vegetarian", "gluten-free"), "None"),

        FoodItem(36, "Pav Bhaji", "Street Food", "cheat", "🥖",
            "Mumbai's famous mashed vegetable curry served with buttery soft pav.",
            520, 12.0, 68.0, 20.0, 8.0, 5, 10, "40 min", "Indian",
            "https://shwetainthekitchen.com/wp-content/uploads/2022/07/Pav-bhaji.jpg",
            "happy,party,hungry,nostalgia",
            listOf("Potatoes", "Cauliflower", "Peas", "Capsicum", "Onion", "Tomatoes", "Pav bhaji masala", "Butter", "Pav"),
            listOf("Boil and mash all vegetables.", "Sauté onions and capsicum.", "Add tomatoes and masala, cook.", "Add mashed vegetables, simmer 15 min.", "Serve with butter-toasted pav."),
            listOf("vegetarian"), "Gluten, Dairy"),

        FoodItem(37, "Butter Chicken", "Indian Main", "cheat", "🍗",
            "Tender chicken in velvety tomato-cream sauce — best Indian comfort food.",
            580, 35.0, 24.0, 36.0, 3.0, 5, 10, "50 min", "North Indian",
            "https://cdn.apartmenttherapy.info/image/upload/f_jpg,q_auto:eco,c_fill,g_auto,w_1500,ar_1:1/k%2FPhoto%2FRecipes%2F2024-12-butter-chicken%2Fbutter-chicken-323",
            "party,happy,weekend,hungry",
            listOf("500g chicken", "Tomatoes", "Onion", "Cashews", "Cream", "Butter", "Ginger-garlic paste", "Spices"),
            listOf("Marinate chicken in yogurt and spices, grill.", "Blend tomatoes, onion, cashews.", "Cook sauce in butter, add grilled chicken.", "Simmer, add cream and honey.", "Serve with naan or rice."),
            listOf("high-protein"), "Dairy, Nuts"),

        FoodItem(38, "Mac and Cheese", "Comfort Food", "cheat", "🧀",
            "Creamy mac and cheese made with whole wheat pasta and reduced-fat cheese.",
            480, 20.0, 58.0, 18.0, 4.0, 5, 10, "25 min", "American",
            "https://www.yummytummyaarthi.com/wp-content/uploads/2024/01/mac-and-cheese-1.jpg",
            "comfort,stressed,happy",
            listOf("Whole wheat macaroni", "Cheddar cheese", "Milk", "Whole wheat flour", "Butter", "Mustard", "Paprika"),
            listOf("Cook pasta al dente.", "Make roux with butter and flour.", "Add milk, whisk until thick.", "Add cheese, mustard and paprika.", "Combine with pasta and serve."),
            listOf("vegetarian"), "Gluten, Dairy"),

        FoodItem(39, "Baked Samosa", "Snack", "cheat", "🥟",
            "Oven-baked samosas with spiced potato filling — all the taste, less the guilt.",
            280, 6.0, 42.0, 10.0, 4.0, 6, 9, "50 min", "Indian",
            "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800",
            "snack,party,happy",
            listOf("Whole wheat dough", "Potatoes", "Peas", "Cumin", "Garam masala", "Chilli", "Coriander", "Oil"),
            listOf("Make dough and rest 30 min.", "Boil and spice potatoes and peas.", "Shape dough into cones, fill with mixture.", "Seal edges and brush with oil.", "Bake at 190°C for 25-30 min."),
            listOf("vegetarian", "baked"), "Gluten"),

        FoodItem(40, "Pasta Arrabbiata", "Italian", "cheat", "🍝",
            "Spicy tomato pasta with garlic and herbs — flavour-packed Italian classic.",
            480, 16.0, 78.0, 12.0, 5.0, 6, 9, "20 min", "Italian",
            "https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=800",
            "weekend,happy,quick",
            listOf("Whole wheat pasta", "Canned tomatoes", "Garlic", "Red chilli flakes", "Olive oil", "Basil", "Parmesan", "Salt"),
            listOf("Cook pasta in salted water.", "Sauté garlic in olive oil.", "Add chilli flakes and tomatoes, simmer 10 min.", "Toss pasta with sauce.", "Finish with basil and parmesan."),
            listOf("vegetarian"), "Gluten, Dairy"),

        FoodItem(41, "Waffles with Berries", "Breakfast", "cheat", "🧇",
            "Crispy whole grain waffles topped with fresh berries and light whipped cream.",
            440, 10.0, 64.0, 15.0, 4.0, 6, 10, "20 min", "American",
            "https://images.unsplash.com/photo-1562376552-0d160a2f238d?w=800",
            "weekend,happy,sweet",
            listOf("Whole wheat flour", "Eggs", "Milk", "Butter", "Baking powder", "Honey", "Berries", "Light whipped cream"),
            listOf("Mix dry ingredients, then wet.", "Combine gently — don't over-mix.", "Pour batter into waffle iron.", "Cook until golden and crispy.", "Top with berries and cream."),
            listOf("vegetarian"), "Gluten, Dairy, Eggs"),

        FoodItem(42, "Nachos with Salsa", "Snack", "cheat", "🫔",
            "Baked tortilla chips with fresh tomato salsa, guacamole and light cheese.",
            420, 10.0, 52.0, 20.0, 6.0, 5, 10, "15 min", "Mexican",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzfNbxtg8wbfuq-kjrlRSHIYAEEJk2c8mLRg&s",
            "party,snack,happy",
            listOf("Corn tortilla chips", "Tomatoes", "Avocado", "Jalapeños", "Lime", "Coriander", "Red onion", "Light cheese"),
            listOf("Layer chips on baking sheet.", "Sprinkle cheese, bake 5 min.", "Dice tomatoes, onion, jalapeño for salsa.", "Mash avocado with lime for guac.", "Top chips with salsa and guac."),
            listOf("vegetarian", "gluten-free"), "Dairy"),

        FoodItem(43, "Chole Bhature", "Street Food", "cheat", "🫘",
            "Spiced chickpea curry with fluffy fried bread — a North Indian weekend favourite.",
            640, 18.0, 82.0, 26.0, 12.0, 5, 10, "60 min", "North Indian",
            "https://madhurasrecipe.com/wp-content/uploads/2025/09/MR-Chole-Bhature-featured-585x585.jpg",
            "weekend,party,hungry",
            listOf("Canned chickpeas", "Onion", "Tomatoes", "Chole masala", "Oil", "Maida", "Curd", "Baking powder"),
            listOf("Prepare chole curry with spices.", "Make bhature dough and rest 1 hr.", "Roll and deep fry bhature.", "Serve hot chole with bhature.", "Garnish with onion rings and pickle."),
            listOf("vegetarian"), "Gluten"),

        FoodItem(44, "Chocolate Mug Cake", "Dessert", "cheat", "🍫",
            "2-minute microwave chocolate cake — satisfies cravings with minimal effort.",
            310, 6.0, 42.0, 14.0, 2.0, 4, 10, "2 min", "Modern",
            "https://www.jessicagavin.com/wp-content/uploads/2022/02/chocolate-mug-cake-16-1200.jpg",
            "sweet,craving,quick,stressed",
            listOf("4 tbsp whole wheat flour", "4 tbsp cocoa", "3 tbsp sugar", "1 egg", "3 tbsp milk", "3 tbsp oil", "Dark chocolate chips"),
            listOf("Mix all dry ingredients in a mug.", "Add egg, milk and oil, mix well.", "Stir in chocolate chips.", "Microwave 90 seconds on high.", "Let cool 1 minute, serve."),
            listOf("vegetarian"), "Gluten, Dairy, Eggs"),

        FoodItem(45, "Veg Biryani", "Indian Main", "cheat", "🍛",
            "Fragrant basmati rice layered with spiced vegetables and saffron.",
            520, 12.0, 82.0, 16.0, 8.0, 6, 10, "60 min", "Indian",
            "https://www.cookingcarnival.com/wp-content/uploads/2025/09/Vegetable-Dum-Biryani-5.jpg",
            "party,weekend,happy",
            listOf("Basmati rice", "Mixed vegetables", "Fried onions", "Saffron milk", "Biryani masala", "Ghee", "Mint", "Coriander"),
            listOf("Cook rice 70% done.", "Prepare vegetable masala.", "Layer rice and masala in pot.", "Add saffron milk and fried onions.", "Dum cook on low heat 20 min."),
            listOf("vegetarian"), "Dairy"),

        FoodItem(46, "Steamed Momos", "Street Food", "cheat", "🥟",
            "Tibetan steamed dumplings with juicy vegetable filling.",
            260, 10.0, 38.0, 7.0, 3.0, 6, 9, "45 min", "Tibetan",
            "https://cdn.foodaciously.com/static/recipes/ee9fd204-25cf-4e97-be5a-d7626470d420/easy-vegan-momos-recipe-7ab341154a5c13d6d9642300e7e2c92d-640.jpg",
            "snack,party,happy",
            listOf("Maida", "Cabbage", "Carrot", "Spring onion", "Ginger", "Garlic", "Soy sauce", "Sesame oil"),
            listOf("Make smooth dough, rest 30 min.", "Finely chop all veggies for filling.", "Roll thin circles, fill and pleat.", "Steam in bamboo steamer 12-15 min.", "Serve with red chilli chutney."),
            listOf("vegetarian", "steamed"), "Gluten, Soy"),

        FoodItem(47, "Egg Fried Rice", "Asian", "cheat", "🍳",
            "Restaurant-style fried rice with eggs, vegetables and soy sauce.",
            440, 16.0, 62.0, 14.0, 3.0, 6, 9, "20 min", "Chinese",
            "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800",
            "quick,hungry,comfort",
            listOf("2 cups cooked rice", "3 eggs", "Mixed vegetables", "Spring onion", "Soy sauce", "Sesame oil", "Ginger", "Garlic"),
            listOf("Use day-old rice for best results.", "Scramble eggs in wok, set aside.", "Fry garlic and ginger, add vegetables.", "Add rice, stir-fry on high heat.", "Add eggs, soy sauce and sesame oil."),
            listOf("vegetarian"), "Eggs, Soy, Gluten"),

        FoodItem(48, "Aloo Paratha", "Breakfast", "cheat", "🥙",
            "Whole wheat flatbread stuffed with spiced mashed potatoes — breakfast royalty.",
            420, 10.0, 62.0, 14.0, 5.0, 6, 9, "30 min", "North Indian",
            "https://static.toiimg.com/thumb/53109843.cms?imgsize=244340&width=800&height=800",
            "weekend,comfort,hungry",
            listOf("Whole wheat flour", "Potatoes", "Onion", "Green chilli", "Cumin", "Coriander", "Ghee", "Curd"),
            listOf("Make dough and rest 20 min.", "Mash potatoes with spices.", "Stuff dough with filling.", "Roll carefully and cook on tawa.", "Serve with ghee and curd."),
            listOf("vegetarian"), "Gluten, Dairy"),

        FoodItem(49, "Light Banana Split", "Dessert", "cheat", "🍨",
            "Fresh banana with low-fat frozen yogurt, berries and dark chocolate.",
            320, 7.0, 58.0, 8.0, 4.0, 6, 9, "10 min", "American",
            "https://foxeslovelemons.com/wp-content/uploads/2021/06/Caramelized-Banana-Split-3.jpg",
            "sweet,summer,happy",
            listOf("2 bananas", "Low-fat frozen yogurt", "Strawberries", "Blueberries", "Dark chocolate", "Walnuts"),
            listOf("Slice bananas lengthwise.", "Add scoops of frozen yogurt.", "Add berries on top.", "Melt dark chocolate, drizzle over.", "Sprinkle walnuts."),
            listOf("vegetarian", "lower-calorie-dessert"), "Dairy, Nuts"),

        FoodItem(50, "Veggie Tacos", "Mexican", "cheat", "🌮",
            "Corn tortillas filled with black beans, roasted corn, avocado and pico de gallo.",
            380, 12.0, 58.0, 12.0, 10.0, 6, 10, "20 min", "Mexican",
            "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800",
            "happy,party,weekend",
            listOf("Corn tortillas", "Black beans", "Corn", "Avocado", "Tomato", "Red onion", "Coriander", "Lime", "Jalapeño"),
            listOf("Warm corn tortillas on dry pan.", "Heat black beans with cumin.", "Roast corn until charred.", "Dice tomato, onion for pico de gallo.", "Assemble tacos and serve with lime."),
            listOf("vegan", "gluten-free"), "None"),

        // Foods 51-100
        FoodItem(51,"Cheesy Garlic Bread","Snack","cheat","🧄","Toasted bread with garlic butter and melted cheese — classic comfort snack.",380,12.0,46.0,18.0,2.0,4,10,"15 min","Italian","https://images.unsplash.com/photo-1573140401552-3fab0b24306f?w=800","party,snack,happy", listOf("Baguette","Butter","Garlic","Mozzarella","Parsley","Chilli flakes"), listOf("Mix softened butter with garlic and parsley.","Slice baguette.","Spread garlic butter generously.","Top with mozzarella.","Broil until golden and bubbly."), listOf("vegetarian"),"Gluten, Dairy"),
        FoodItem(52,"Baked Chicken Wings","Snack","cheat","🍗","Crispy baked chicken wings with buffalo sauce — oven-baked not deep fried!",380,34.0,8.0,22.0,0.0,6,10,"50 min","American","https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=800","party,weekend,hungry", listOf("1kg chicken wings","Baking powder","Salt","Pepper","Hot sauce","Butter","Garlic powder"), listOf("Pat wings very dry.","Toss with baking powder and salt.","Bake at 220°C for 45 min, flipping once.","Toss in hot sauce and butter.","Serve with dip."), listOf("high-protein","gluten-free","baked"),"Dairy"),
        FoodItem(53,"Dark Chocolate Bark","Dessert","cheat","🍫","Rich dark chocolate bark with almonds, cranberries and sea salt.",240,5.0,22.0,16.0,3.0,7,9,"15 min","Modern","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFVYqAJ-Nko4jf9u5qhiQT--kxLwzvONqXdw&s","sweet,craving,snack", listOf("200g dark chocolate 70%","Almonds","Dried cranberries","Sea salt flakes","Pumpkin seeds"), listOf("Melt chocolate in double boiler.","Pour thin layer on parchment.","Scatter almonds, cranberries and seeds.","Sprinkle sea salt.","Refrigerate until set, break into pieces."), listOf("vegan","gluten-free","antioxidant-rich"),"Nuts"),
        FoodItem(54,"Chicken Biryani","Indian Main","cheat","🍛","Slow-cooked aromatic chicken biryani with basmati rice.",620,38.0,72.0,20.0,4.0,5,10,"90 min","Hyderabadi","https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?w=800","party,weekend,happy", listOf("Chicken","Basmati rice","Fried onions","Saffron","Biryani masala","Yogurt","Mint","Ghee"), listOf("Marinate chicken in yogurt and spices.","Cook rice 70%.","Brown chicken in heavy pot.","Layer rice over chicken.","Dum cook sealed for 30 min."), listOf("high-protein"),"Dairy"),
        FoodItem(55,"Paneer Butter Masala","Indian Main","cheat","🧀","Creamy tomato gravy with soft paneer cubes — rich and indulgent.",540,22.0,24.0,38.0,4.0,5,10,"40 min","North Indian","https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800","weekend,party,comfort", listOf("Paneer","Tomatoes","Cashews","Cream","Butter","Ginger-garlic paste","Kashmiri chilli","Spices"), listOf("Blend tomatoes and cashews into smooth sauce.","Cook with butter and spices.","Add paneer cubes.","Simmer with cream.","Serve with naan."), listOf("vegetarian"),"Dairy, Nuts"),
        FoodItem(56,"Chocolate Milkshake","Drinks","cheat","🥛","Thick and creamy chocolate milkshake made with dark cocoa.",380,10.0,62.0,10.0,2.0,5,10,"5 min","American","https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800","sweet,happy,craving", listOf("2 cups low-fat milk","3 tbsp dark cocoa","2 scoops vanilla ice cream","2 tbsp honey","Vanilla extract"), listOf("Blend all ingredients until smooth.","Taste and adjust sweetness.","Pour into chilled glass.","Top with a little whipped cream.","Serve immediately."), listOf("vegetarian"),"Dairy"),
        FoodItem(57,"Spaghetti Bolognese","Italian","cheat","🍝","Classic meat sauce with whole wheat spaghetti.",560,32.0,66.0,18.0,6.0,6,9,"45 min","Italian","https://www.slimmingeats.com/blog/wp-content/uploads/2010/04/spaghetti-bolognese-36.jpg","weekend,hungry,comfort", listOf("Whole wheat spaghetti","Lean minced beef","Tomatoes","Onion","Garlic","Carrot","Celery","Red wine","Herbs"), listOf("Brown beef in pot.","Add onion, garlic, carrot, celery.","Add tomatoes and wine, simmer 30 min.","Cook pasta al dente.","Toss and serve with parmesan."), listOf("high-protein"),"Gluten, Dairy"),
        FoodItem(58,"Hakka Noodles","Asian","cheat","🍜","Indo-Chinese hakka noodles with colourful vegetables and soy sauce.",460,14.0,72.0,14.0,5.0,5,10,"20 min","Indo-Chinese","https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?w=800","quick,happy,weekend", listOf("Hakka noodles","Cabbage","Carrot","Spring onion","Bell pepper","Garlic","Soy sauce","Vinegar","Chilli sauce","Oil"), listOf("Boil noodles until just done.","Stir-fry garlic in hot oil.","Add vegetables on high flame.","Add noodles, soy sauce, vinegar.","Toss everything on high heat."), listOf("vegetarian"),"Gluten, Soy"),
        FoodItem(59,"Gulab Jamun","Dessert","cheat","🍮","Small bite-sized gulab jamuns soaked in rose syrup.",280,5.0,48.0,8.0,1.0,4,10,"40 min","Indian","https://pipingpotcurry.com/wp-content/uploads/2023/12/Gulab-Jamun-Recipe-Piping-Pot-Curry.jpg","sweet,festival,happy", listOf("Khoya","Paneer","Maida","Cardamom","Sugar","Rose water","Saffron","Oil"), listOf("Knead khoya, paneer and maida.","Roll into small balls.","Deep fry on low heat until golden.","Soak in warm sugar syrup with rose water.","Serve warm with ice cream."), listOf("vegetarian"),"Dairy, Gluten"),
        FoodItem(60,"Cheese Dosa","South Indian","cheat","🧀","Crispy dosa filled with spiced potato and melted cheese.",520,14.0,72.0,20.0,4.0,5,10,"30 min","Fusion","https://www.indianhealthyrecipes.com/wp-content/uploads/2016/09/cheese-dosa-recipe.jpg","weekend,hungry,happy", listOf("Dosa batter","Mozzarella","Potatoes","Onion","Masala","Ghee","Chutney"), listOf("Prepare spiced potato filling.","Spread dosa on hot tawa.","Add filling and sprinkle cheese.","Fold when cheese melts.","Serve with chutney and sambar."), listOf("vegetarian"),"Dairy"),
        FoodItem(61,"Poached Eggs on Spinach","Breakfast","eat","🥚","Perfectly poached eggs on wilted spinach with lemon.",200,18.0,8.0,12.0,4.0,9,8,"15 min","Continental","https://eatingrules.com/wp-content/uploads/2014/10/skillet-poached-eggs-with-spinach.jpg","morning,focused,light", listOf("3 eggs","200g spinach","Garlic","Lemon","Olive oil","Salt","Pepper"), listOf("Wilt spinach with garlic in olive oil.","Poach eggs in simmering water.","Season spinach and plate.","Top with eggs.","Squeeze lemon and serve."), listOf("vegetarian","high-protein","low-carb"),"Eggs"),
        FoodItem(62,"Watermelon Feta Salad","Salad","eat","🍉","Refreshing summer salad with watermelon, feta, mint and balsamic.",180,7.0,28.0,6.0,1.0,9,9,"10 min","Mediterranean","https://www.cubesnjuliennes.com/wp-content/uploads/2021/03/Watermelon-Feta-Salad-Recipe.jpg","summer,happy,light", listOf("4 cups watermelon","100g feta","Fresh mint","Balsamic glaze","Black pepper","Olive oil"), listOf("Cube watermelon.","Crumble feta over it.","Add torn mint leaves.","Drizzle balsamic glaze and olive oil.","Season with pepper and serve."), listOf("vegetarian","gluten-free","refreshing"),"Dairy"),
        FoodItem(63,"Tandoori Chicken","Indian Main","eat","🍗","Char-grilled chicken in smoky yogurt marinade.",320,42.0,8.0,12.0,1.0,8,10,"60 min","North Indian","https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800","party,hungry,happy", listOf("Chicken legs","Yogurt","Tandoori masala","Ginger-garlic paste","Kashmiri chilli","Lemon","Oil"), listOf("Score chicken and marinate in yogurt and spices for 4 hrs.","Grill in oven at 220°C for 30 min.","Turn and grill 10 more min.","Char on open flame for smoky flavour.","Serve with onion rings and lemon."), listOf("high-protein","gluten-free"),"Dairy"),
        FoodItem(64,"Idli with Sambhar","South Indian","eat","🫓","Fluffy steamed rice cakes with lentil vegetable stew.",280,10.0,48.0,4.0,5.0,9,8,"30 min","South Indian","https://vaya.in/recipes/wp-content/uploads/2018/02/Idli-and-Sambar-1.jpg","morning,light,healthy", listOf("Idli batter","Toor dal","Vegetables","Tamarind","Sambhar masala","Mustard seeds","Curry leaves"), listOf("Steam idli in moulds for 12 min.","Cook dal with tamarind and veggies.","Make tempering with mustard and curry leaves.","Add sambhar masala and simmer.","Serve hot idlis with sambhar and chutney."), listOf("vegetarian","gluten-free","probiotic"),"None"),
        FoodItem(65,"Veg Sushi Rolls","Asian","eat","🍣","Fresh vegetable sushi rolls with cucumber, avocado and pickled ginger.",290,7.0,52.0,6.0,3.0,8,8,"40 min","Japanese","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIKDPBk5NhlHhutniIVNVZ80RyHdyLzmFIkA&s","happy,light,focused", listOf("Sushi rice","Nori sheets","Cucumber","Avocado","Carrot","Cream cheese","Soy sauce","Pickled ginger"), listOf("Cook and season sushi rice.","Lay nori on bamboo mat.","Spread rice, add fillings.","Roll tightly with mat.","Slice and serve with soy sauce."), listOf("vegetarian"),"Soy, Dairy"),
        FoodItem(66,"Upma","Breakfast","eat","🍚","Semolina porridge tempered with vegetables and curry leaves.",270,8.0,44.0,7.0,3.0,8,7,"20 min","South Indian","https://rakskitchen.net/wp-content/uploads/2013/02/upma-recipe-feat-500x375.jpg","morning,quick,comfort", listOf("1 cup semolina","Onion","Green chilli","Carrot","Peas","Mustard seeds","Curry leaves","Ghee","Cashews"), listOf("Dry roast semolina until fragrant.","Sauté mustard, curry leaves, veggies.","Add 2.5 cups boiling water.","Add semolina, stir until thick.","Finish with ghee and cashews."), listOf("vegetarian"),"Gluten, Dairy, Nuts"),
        FoodItem(67,"Mango Lassi","Drinks","eat","🥭","Refreshing yogurt-based mango drink — natural, cooling and probiotic-rich.",220,7.0,42.0,4.0,2.0,8,10,"5 min","Indian","https://www.yellowthyme.com/wp-content/uploads/2023/03/Mango-Lassi-08589.jpg","summer,happy,refreshing", listOf("1 cup curd","1 cup mango pulp","Milk","Sugar","Cardamom","Ice"), listOf("Blend curd, mango pulp, and milk.","Add sugar and cardamom.","Blend until frothy.","Pour over ice and serve."), listOf("vegetarian","probiotic"),"Dairy"),
        FoodItem(68,"Chia Pudding","Breakfast","eat","🫙","Creamy coconut milk chia pudding topped with tropical fruits.",290,8.0,36.0,12.0,10.0,9,8,"5 min","Modern","https://www.jessicagavin.com/wp-content/uploads/2023/06/how-to-make-chia-pudding-23-1200.jpg","morning,quick,prep", listOf("4 tbsp chia seeds","1 cup coconut milk","Honey","Vanilla","Mango","Kiwi","Coconut flakes"), listOf("Mix chia seeds with coconut milk, honey and vanilla.","Stir well and refrigerate overnight.","In the morning, top with fruit.","Add coconut flakes and serve."), listOf("vegan","gluten-free","omega-3-rich"),"None"),
        FoodItem(69,"Trail Mix","Snack","eat","🥜","A balanced trail mix of almonds, walnuts, cashews and dried berries.",200,6.0,18.0,13.0,3.0,8,8,"2 min","Universal","https://www.eazypeazymealz.com/wp-content/uploads/2024/01/Easy-Trail-Mix-12.jpg","snack,quick,energetic", listOf("Almonds","Walnuts","Cashews","Dried cranberries","Dried apricots","Pumpkin seeds"), listOf("Combine all nuts and seeds.","Add dried fruits.","Portion into 30g servings.","Store in airtight container."), listOf("vegan","gluten-free","nutrient-dense"),"Nuts"),
        FoodItem(70,"Beetroot Hummus","Snack","eat","🫐","Vibrant pink beetroot hummus with chickpeas, tahini and lemon.",140,6.0,18.0,6.0,5.0,9,8,"20 min","Middle Eastern","https://www.noracooks.com/wp-content/uploads/2025/01/beet-hummus-1-2.jpg","snack,diet,happy", listOf("1 can chickpeas","2 roasted beetroots","Tahini","Lemon","Garlic","Olive oil","Salt","Cumin"), listOf("Roast beetroot at 200°C for 45 min.","Blend chickpeas with tahini and garlic.","Add beetroot and lemon juice.","Blend until smooth.","Drizzle olive oil and serve with veggies."), listOf("vegan","gluten-free","high-fiber"),"Sesame"),
        FoodItem(71,"Whole Wheat Wrap","Lunch","eat","🫔","Whole wheat wrap stuffed with grilled chicken, lettuce, hummus and veggies.",380,32.0,38.0,10.0,5.0,8,9,"15 min","Modern","https://smilesandwich.com/wp-content/uploads/2017/01/Breakfast-Burritos-2-540x720.jpg","quick,focused,lunch", listOf("Whole wheat wrap","Grilled chicken","Lettuce","Tomato","Cucumber","Hummus","Red onion","Lemon"), listOf("Spread hummus on wrap.","Layer chicken and vegetables.","Squeeze lemon over filling.","Roll tightly and cut in half.","Serve."), listOf("high-protein"),"Gluten"),
        FoodItem(72,"Ragi Mudde","Indian","eat","🫓","Finger millet balls — incredibly nutritious staple from Karnataka.",250,8.0,48.0,3.0,6.0,10,6,"20 min","Karnataka","https://www.sharmispassions.com/wp-content/uploads/2019/06/ragi-mudde5.jpg","health,diet,nutrition", listOf("1 cup ragi flour","2 cups water","Salt"), listOf("Boil water with salt.","Add ragi flour gradually while stirring.","Cook on low heat, stir continuously.","Form into smooth balls when done.","Serve with sambhar or curry."), listOf("vegan","gluten-free","calcium-rich"),"None"),
        FoodItem(73,"Rasam","South Indian","eat","🍲","Thin peppery tamarind soup — loaded with antioxidants.",80,3.0,14.0,2.0,2.0,10,7,"20 min","South Indian","https://www.indianhealthyrecipes.com/wp-content/uploads/2022/01/rasam.jpg","sick,tired,cold,immunity", listOf("Tamarind","Tomatoes","Black pepper","Cumin","Garlic","Curry leaves","Mustard seeds","Ghee"), listOf("Soak and extract tamarind juice.","Boil with tomatoes and spices.","Prepare ghee tempering.","Pour over rasam.","Serve hot."), listOf("vegan","gluten-free","immunity-boosting"),"None"),
        FoodItem(74,"Soya Chunks Curry","Indian Main","eat","🫘","High-protein textured soy chunks in a spiced onion-tomato gravy.",310,28.0,28.0,8.0,5.0,9,8,"30 min","Indian","https://www.secondrecipe.com/wp-content/uploads/2024/10/Nutrela-soy-chunk-curry.jpg","muscle,diet,protein", listOf("2 cups soya chunks","Onion","Tomatoes","Ginger-garlic","Spices","Yogurt","Oil","Coriander"), listOf("Boil soya chunks, squeeze water.","Sauté onions golden.","Add ginger-garlic, tomatoes, spices.","Add soya and yogurt, simmer.","Garnish with coriander."), listOf("vegetarian","high-protein","gluten-free"),"Soy, Dairy"),
        FoodItem(75,"Peanut Butter Toast","Breakfast","eat","🥜","Multigrain toast with natural peanut butter, banana slices and honey.",340,14.0,42.0,14.0,5.0,8,9,"5 min","American","https://img.sndimg.com/food/image/upload/q_92,fl_progressive,w_1200,c_scale/v1/img/recipes/16/31/92/picQ4yJSa.jpg","morning,quick,energetic", listOf("2 multigrain bread slices","2 tbsp peanut butter","1 banana","Honey","Chia seeds"), listOf("Toast bread until golden.","Spread peanut butter generously.","Layer banana slices.","Drizzle honey.","Sprinkle chia seeds."), listOf("vegetarian","high-protein"),"Gluten, Peanuts"),
        FoodItem(76,"Greek Salad","Salad","eat","🥗","Rustic Greek salad with cucumbers, olives, feta and oregano.",200,8.0,14.0,14.0,4.0,9,9,"10 min","Greek","https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=800","summer,light,happy", listOf("Cucumber","Cherry tomatoes","Kalamata olives","Feta cheese","Red onion","Olive oil","Dried oregano","Lemon"), listOf("Chop cucumber and tomatoes.","Add olives and sliced red onion.","Top with feta slab.","Drizzle olive oil.","Season with oregano and salt."), listOf("vegetarian","gluten-free","mediterranean"),"Dairy"),
        FoodItem(77,"Methi Thepla","Breakfast","eat","🫓","Whole wheat flatbread with fresh fenugreek leaves.",240,8.0,36.0,7.0,4.0,8,8,"25 min","Gujarati","https://www.indubenkhakhrawala.com/wp-content/uploads/2025/04/Gujarati-Methi-Thepla-Made-By-Induben-Khakhrawala.jpg","morning,travel,quick", listOf("Whole wheat flour","Fresh methi leaves","Curd","Ginger","Green chilli","Turmeric","Cumin","Oil"), listOf("Mix flour with chopped methi and all spices.","Add curd, form dough.","Rest 15 min.","Roll thin and cook on tawa with oil.","Serve with curd and pickle."), listOf("vegetarian"),"Gluten, Dairy"),
        FoodItem(78,"Steamed Broccoli","Side","eat","🥦","Tender steamed broccoli with a sprinkle of parmesan.",130,9.0,10.0,7.0,5.0,9,7,"10 min","Continental","https://www.saffrontrail.com/wp-content/uploads/2018/01/microwave-steamed-broccoli-01-1.jpeg","light,diet,quick", listOf("300g broccoli","Parmesan","Lemon","Salt","Pepper"), listOf("Cut broccoli into florets.","Steam 5-7 minutes.","Dress with lemon.","Season with salt and pepper.","Sprinkle parmesan."), listOf("vegetarian","gluten-free","low-carb"),"Dairy"),
        FoodItem(79,"Miso Soup","Soup","eat","🍜","Comforting Japanese miso soup with silken tofu and seaweed.",80,7.0,8.0,3.0,2.0,9,7,"10 min","Japanese","https://assets.epicurious.com/photos/63ceb68b7d88c936746ada44/4:3/w_5197,h_3898,c_limit/MisoSoup_RECIPE_012023_46093.jpg","light,focused,sick", listOf("3 cups water","2 tbsp miso paste","150g silken tofu","Wakame seaweed","Spring onion"), listOf("Bring water to gentle simmer.","Dissolve miso paste in a little water.","Add miso to pot — don't boil.","Add cubed tofu and rehydrated seaweed.","Serve with spring onion."), listOf("vegan","gluten-free","probiotic"),"Soy"),
        FoodItem(80,"Coconut Water","Drinks","eat","🥥","Nature's electrolyte drink — raw coconut water.",60,1.0,14.0,0.0,0.0,10,9,"1 min","Tropical","https://images.immediate.co.uk/production/volatile/sites/30/2024/06/Coconut-water440-c1acff0.jpg","summer,refreshing,sports", listOf("1 fresh coconut"), listOf("Open tender coconut.","Pour water into glass.","Optionally add lime.","Serve chilled or over ice."), listOf("vegan","gluten-free","hydrating"),"None"),
        FoodItem(81,"Chicken Tacos","Mexican","cheat","🌮","Soft flour tortillas with seasoned grilled chicken and salsa.",460,30.0,50.0,16.0,4.0,6,10,"25 min","Mexican","https://static01.nyt.com/images/2025/05/14/multimedia/kf-easy-chicken-tacos-gwfh/kf-easy-chicken-tacos-gwfh-mediumSquareAt3X.jpg","party,happy,weekend", listOf("Flour tortillas","Chicken breast","Taco seasoning","Salsa","Sour cream","Lettuce","Cheese","Lime"), listOf("Season and grill chicken.","Slice thinly.","Warm tortillas on pan.","Fill with chicken and toppings.","Serve with lime wedges."), listOf("high-protein"),"Gluten, Dairy"),
        FoodItem(82,"Quesadillas","Mexican","cheat","🫔","Crispy quesadillas with cheese, beans, peppers and salsa.",480,18.0,54.0,22.0,6.0,6,10,"15 min","Mexican","https://cdn.apartmenttherapy.info/image/upload/f_jpg,q_auto:eco,c_fill,g_auto,w_1500,ar_4:3/k%2FPhoto%2FRecipes%2F2025-02-quesadilla%2Fquesadilla-449","quick,hungry,party", listOf("Flour tortillas","Cheddar cheese","Black beans","Bell peppers","Salsa","Sour cream","Jalapeño"), listOf("Lay tortilla in pan on medium heat.","Add cheese, beans, peppers on one half.","Fold over and press down.","Cook until golden on both sides.","Cut and serve with salsa."), listOf("vegetarian"),"Gluten, Dairy"),
        FoodItem(83,"Baked Spring Rolls","Asian","cheat","🥟","Crispy baked spring rolls with vegetable filling.",220,5.0,34.0,8.0,3.0,6,9,"40 min","Chinese","https://www.connoisseurusveg.com/wp-content/uploads/2022/04/baked-spring-rolls-sq.jpg","snack,party,happy", listOf("Spring roll sheets","Cabbage","Carrot","Glass noodles","Ginger","Garlic","Soy sauce","Sesame oil"), listOf("Sauté vegetables with ginger and garlic.","Add noodles and soy sauce.","Cool filling completely.","Roll in spring roll sheets.","Bake at 200°C for 20 min."), listOf("vegetarian","baked"),"Gluten, Soy"),
        FoodItem(84,"Kulfi","Dessert","cheat","🍨","Traditional Indian frozen dessert with cardamom and pistachios.",240,6.0,34.0,9.0,1.0,5,9,"15 min","Indian","https://c.ndtvimg.com/2020-04/0n0vnkm8_kulfi_625x300_13_April_20.jpg","summer,sweet,happy", listOf("Full-fat milk","Condensed milk","Cardamom","Pistachios","Saffron","Rose water"), listOf("Reduce milk to half by simmering.","Add condensed milk and cardamom.","Stir in saffron and rose water.","Pour into kulfi moulds.","Freeze overnight."), listOf("vegetarian","gluten-free"),"Dairy, Nuts"),
        FoodItem(85,"Air-Fried Chicken","Fast Food","cheat","🍗","Crispy chicken in the air fryer — all the crunch, way less oil.",380,34.0,24.0,16.0,2.0,6,10,"30 min","American","https://food.fnr.sndimg.com/content/dam/images/food/fullset/2020/07/14/0/FNK_AIR-FRYER-FRIED-CHICKEN_H-f_s4x3.jpg.rend.hgtvcom.1280.1280.suffix/1594744001146.webp","party,hungry,weekend", listOf("Chicken pieces","Buttermilk","Flour","Paprika","Garlic powder","Egg","Breadcrumbs"), listOf("Marinate chicken in buttermilk 1 hr.","Coat in flour and spice mixture.","Dip in egg, then breadcrumbs.","Air fry at 200°C for 20 min.","Flip halfway through."), listOf("high-protein","air-fried"),"Gluten, Dairy, Eggs"),
        FoodItem(86,"Pasta Carbonara","Italian","cheat","🍝","Classic Italian pasta with silky egg and parmesan sauce.",560,24.0,68.0,20.0,3.0,5,10,"20 min","Italian","https://www.simplyrecipes.com/thmb/0UeN5LhKq-ze3BcZJ7_Yp803T24=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Simply-Pasta-Carbonara-LEAD-1-c477cc25c7294cd9a3fc51ece176481f.jpg","weekend,comfort,hungry", listOf("Whole wheat spaghetti","Eggs","Parmesan","Pancetta","Black pepper","Garlic"), listOf("Cook pasta in salted water.","Crisp pancetta in pan.","Whisk eggs with parmesan.","Toss hot pasta with pancetta off heat.","Add egg mixture and toss quickly."), listOf(),"Gluten, Dairy, Eggs"),
        FoodItem(87,"Malai Kofta","Indian Main","cheat","🧀","Soft paneer and potato balls in rich cashew-tomato cream gravy.",580,18.0,42.0,38.0,4.0,4,10,"60 min","North Indian","https://i0.wp.com/pistachiodoughnut.com/wp-content/uploads/2025/07/IMG_2441_jpg.jpg?resize=800%2C856&ssl=1","party,weekend,occasion", listOf("Paneer","Potatoes","Cashews","Cream","Tomatoes","Spices","Oil","Butter"), listOf("Mash paneer and potato, make balls.","Deep fry until golden.","Blend cashew-tomato sauce.","Cook sauce with butter and spices.","Add fried koftas, serve."), listOf("vegetarian"),"Dairy, Nuts"),
        FoodItem(88,"Onion Pakoda","Snack","cheat","🧅","Crispy besan-fried onion fritters — monsoon snack.",280,8.0,36.0,12.0,4.0,5,10,"20 min","Indian","https://www.sharmispassions.com/wp-content/uploads/2022/02/onion-pakoda-recipe4-500x500.jpg","monsoon,snack,happy,rain", listOf("3 onions","1 cup besan","Green chilli","Ginger","Coriander","Cumin seeds","Red chilli powder","Salt","Oil"), listOf("Thinly slice onions.","Mix all ingredients without water.","Add small amount of water if needed.","Deep fry in batches or bake at 200°C.","Serve with ketchup and chai."), listOf("vegetarian","gluten-free"),"Chickpea flour"),
        FoodItem(89,"French Toast","Breakfast","cheat","🍞","Golden custard-dipped bread topped with berries.",380,12.0,52.0,14.0,3.0,6,9,"15 min","American","https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=800","weekend,sweet,breakfast", listOf("Whole grain bread","2 eggs","Milk","Cinnamon","Vanilla","Maple syrup","Berries","Butter"), listOf("Whisk eggs with milk, cinnamon and vanilla.","Dip bread slices.","Cook in buttered pan until golden.","Top with fresh berries.","Drizzle maple syrup."), listOf("vegetarian"),"Gluten, Dairy, Eggs"),
        FoodItem(90,"Shahi Paneer","Indian Main","cheat","👑","Rich and royal paneer in a creamy cashew-saffron gravy.",520,20.0,22.0,38.0,3.0,5,10,"45 min","North Indian","https://indianshealthyrecipes.com/wp-content/uploads/2024/07/ShahiPaneer-3.jpg","occasion,party,happy", listOf("Paneer","Cashews","Cream","Saffron","Cardamom","Onion","Ginger","Spices","Butter"), listOf("Soak cashews and blend smooth.","Cook onion paste golden.","Add cashew paste and saffron milk.","Add paneer, simmer.","Finish with cream."), listOf("vegetarian"),"Dairy, Nuts"),
        FoodItem(91,"Club Sandwich","Snack","cheat","🥪","Triple-decker club sandwich with chicken, egg and light mayo.",480,28.0,46.0,18.0,3.0,6,9,"15 min","American","https://f000.backblazeb2.com/file/recipekit-bucket/20240725081844-chicken-20bacon-20club-20sandwich-20main-20landscape.jpg","lunch,hungry,quick", listOf("3 bread slices","Chicken","Boiled egg","Lettuce","Tomato","Light mayo","Mustard","Cheese"), listOf("Toast all bread slices.","Layer chicken, lettuce, tomato with mayo.","Add second bread layer.","Add sliced egg and cheese.","Top with third slice, cut diagonal."), listOf("high-protein"),"Gluten, Dairy, Eggs"),
        FoodItem(92,"Corn Chaat","Indian Snack","cheat","🌽","Spiced sweet corn with green chutney and chaat masala.",220,5.0,42.0,5.0,5.0,6,9,"10 min","Indian","https://www.whiskaffair.com/wp-content/uploads/2021/06/Indian-Flavored-Corn-Chaat-2-3.jpg","snack,happy,monsoon", listOf("2 cups corn","Green chutney","Tamarind chutney","Chaat masala","Red chilli powder","Lemon","Coriander","Onion"), listOf("Boil or roast corn kernels.","Mix with chutneys.","Add onion, coriander.","Season with chaat masala and chilli.","Squeeze lemon and serve."), listOf("vegan","gluten-free"),"None"),
        FoodItem(93,"Rajma Burger","Fusion","cheat","🍔","Homemade kidney bean patty burger — Indian flavours in Western format.",440,16.0,62.0,14.0,10.0,7,9,"30 min","Fusion","https://www.dwarakaorganic.com/wp-content/uploads/2025/06/Rajma-Burger.jpg","weekend,happy,hungry", listOf("Canned rajma","Onion","Spices","Whole wheat bun","Lettuce","Tomato","Hung curd dressing"), listOf("Mash rajma with spices and onion.","Form patties and pan-fry.","Toast bun.","Layer with lettuce, patty, tomato.","Drizzle curd dressing."), listOf("vegetarian","high-fiber"),"Gluten, Dairy"),
        FoodItem(94,"Tiramisu","Dessert","cheat","☕","Classic Italian dessert with espresso-soaked ladyfingers and mascarpone.",420,8.0,54.0,20.0,1.0,5,10,"30 min","Italian","https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800","occasion,sweet,party", listOf("Ladyfinger biscuits","Strong espresso","Mascarpone","Eggs","Sugar","Dark cocoa"), listOf("Brew strong espresso and cool.","Whip mascarpone with egg yolks and sugar.","Fold in whipped cream.","Dip ladyfingers in espresso briefly.","Layer with cream, dust cocoa and chill 4 hrs."), listOf("vegetarian"),"Gluten, Dairy, Eggs"),
        FoodItem(95,"Cheesecake Slice","Dessert","cheat","🍰","Baked New York cheesecake with fresh berry coulis.",380,7.0,48.0,18.0,1.0,4,10,"70 min","American","https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=800","occasion,sweet,happy", listOf("Cream cheese","Eggs","Sugar","Sour cream","Vanilla","Graham crackers","Butter","Strawberries"), listOf("Make graham cracker base.","Blend cream cheese, eggs, sugar smooth.","Pour over base.","Bake in water bath at 160°C for 50 min.","Cool and refrigerate. Serve with berry coulis."), listOf("vegetarian"),"Gluten, Dairy, Eggs"),
        FoodItem(96,"Chilli Paneer","Indo-Chinese","cheat","🌶️","Crispy paneer in tangy, spicy Indo-Chinese sauce.",440,20.0,36.0,24.0,4.0,5,10,"30 min","Indo-Chinese","https://spicecravings.com/wp-content/uploads/2022/01/Chilli-Paneer-Featured-2.jpg","party,weekend,happy", listOf("Paneer","Bell peppers","Spring onion","Garlic","Soy sauce","Cornflour","Chilli sauce","Vinegar","Oil"), listOf("Coat paneer in cornflour and fry.","Sauté garlic and peppers.","Add sauces and simmer.","Add fried paneer.","Garnish spring onion."), listOf("vegetarian"),"Dairy, Soy, Gluten"),
        FoodItem(97,"Fresh Lemonade","Drinks","cheat","🍋","Fresh squeezed lemonade with mint and chaat masala.",120,0.0,32.0,0.0,0.0,6,9,"5 min","Universal","https://images.unsplash.com/photo-1523677011781-c91d1bbe2f9e?w=800","summer,refreshing,happy", listOf("4 lemons","2 tbsp sugar","Mint leaves","Chaat masala","Water","Ice"), listOf("Juice all lemons.","Dissolve sugar in little warm water.","Combine with lemon juice and water.","Add mint and chaat masala.","Serve over lots of ice."), listOf("vegan","gluten-free"),"None"),
        FoodItem(98,"Vada Pav","Street Food","cheat","🍔","Mumbai's iconic potato vada in pav with chutneys.",380,9.0,56.0,14.0,4.0,5,10,"40 min","Maharashtrian","https://blog.swiggy.com/wp-content/uploads/2024/11/Image-1_mumbai-vada-pav-1024x538.png","nostalgia,happy,snack", listOf("Pav buns","Potatoes","Besan","Turmeric","Mustard seeds","Curry leaves","Green chutney","Dry garlic chutney"), listOf("Make spiced potato balls.","Make besan batter.","Dip potato balls and fry.","Slit pav and add chutneys.","Insert vada and serve hot."), listOf("vegetarian"),"Gluten"),
        FoodItem(99,"Motichoor Ladoo","Dessert","cheat","🟠","Festive Indian sweet made with tiny besan pearls and sugar syrup.",180,3.0,30.0,6.0,1.0,4,9,"45 min","Indian","https://static.toiimg.com/thumb/55048059.cms?imgsize=196306&width=800&height=800","festival,happy,sweet", listOf("Besan","Sugar","Ghee","Cardamom","Saffron","Pistachios","Rose water","Oil"), listOf("Make bundi with besan batter.","Prepare sugar syrup.","Soak bundi in syrup.","Mash and shape into ladoos.","Garnish with pistachios."), listOf("vegetarian","gluten-free"),"Dairy, Nuts"),
        FoodItem(100,"Sev Puri","Street Food","cheat","🥗","Crunchy puris topped with potatoes, chutneys, sev and pomegranate.",290,6.0,46.0,10.0,4.0,5,10,"15 min","Indian","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQs45MBSjs_xFwLMGsopfYdN0KuHtjKlRZpjQ&s","happy,snack,party,monsoon", listOf("Mini puris","Potatoes","Onion","Green chutney","Tamarind chutney","Sev","Pomegranate","Coriander"), listOf("Arrange puris on plate.","Top each with diced potato and onion.","Add both chutneys.","Sprinkle sev generously.","Garnish pomegranate and coriander."), listOf("vegetarian"),"Gluten")
    )
}
